### ISSUE TITLE
Event 'update-device-status' does not recognized IP changes 

### ISSUE THREAD

**Issue by schmupu** [Apollon77/shelly-iot#11]
If the IP address change of available and integrated Shelly device, the Event 'update-device-status' will not be called.
You have first change the status of a Shelly device like pushing the switch button on a Shelly 1. Afterwards the the Event will be change.
Is it possible, that the event will be called after an IP change?

see: https://github.com/schmupu/ioBroker.shelly/issues/70

**Comment by Apollon77** [comment]
Bitte 1.0.3 der Lib von GitHub versuchen

**Comment by schmupu** [comment]
Tested with ioBroker Shelly adapter in Version 3.0.7 and Shelly 1. Works great! 
I changed the dependency of "shelly-iot" in the package.json to version 1.0.3 and wait till you publish it to npmjs
Thanks

**Comment by Apollon77** [comment]
published
