### ISSUE TITLE
Error: send EHOSTDOWN 192.168.20.x:5683

### ISSUE THREAD

**Issue by schmupu** [Apollon77/shelly-iot#2]
Es kommt bei dem Shelly H&T zu folgendem Fehler unten. Der H&T ist immer nur ein paar Sekunden aktiv und dann legt er sich wieder schlafen. D.h. nicht über ping, etc für 1 Std. erreichbar. Wenn der H&T aufwacht tritt folgender Fehler auf:

![shellyerror](https://user-images.githubusercontent.com/38919572/50538695-5ebb7980-0b73-11e9-8c5b-6a10235c1617.jpeg)

VG

**Comment by Apollon77** [comment]
I need a debug log from such a case

**Comment by schmupu** [comment]
okay, here an example. But there are not much information:

`
/usr/local/bin/node --inspect-brk=21917 shelly.js --debug --force --logs --trace-warnings
Debugger listening on ws://127.0.0.1:21917/e9b884b4-ad06-49c7-a08c-579f96c3c6d6
Debugger attached.
starting. Version 3.0.7 in /opt/iobroker/node_modules/iobroker.shelly, node: v8.16.0
Stating Shelly adapter in CoAP modus.
Listening for Shelly packets in the network
CoAP status package received: {"3332":"SHSW-1#5B2C00#1","3412":38400,"3420":256,"Uri-Path":"cit/s"} / {"G":[[0,112,0]]}
Status update received for SHSW-1#5B2C00#1: {"G":[[0,112,0]]}
CoAP device description request for SHSW-1#5B2C00#1 to 192.168.20.134(0)
CoAP device description request for SHSW-1#5B2C00#1 to 192.168.20.134(1)
CoAP device description request for SHSW-1#5B2C00#1 to 192.168.20.134(2)
CoAP status package received: {"3332":"SHSW-1#056EE0#1","3412":38400,"3420":2816,"Uri-Path":"cit/s"} / {"G":[[0,112,0]]}
Status update received for SHSW-1#056EE0#1: {"G":[[0,112,0]]}
CoAP device description request for SHSW-1#056EE0#1 to 192.168.20.241(0)
null: Error: send EHOSTUNREACH 192.168.20.134:5683
Closing Adapter
terminating
Closing Adapter
`

**Comment by Apollon77** [comment]
Schau mal in deinem node_modules nach https://github.com/mcollina/node-coap/blob/master/lib/agent.js#L91 ... und schiebe das "on('error') mal höher im Code ... ich tippe über das "bind". Fehler dann weg? Dann wäre das der fix den man bei denen als PR einreichen müsste

**Comment by schmupu** [comment]
Hat nichts geholfen :-(

```
let shelly = new Shelly(options);
shelly.on('error', (err) => {
      this.adapter.log.info('Error handling Shelly data: ' + err);
});
shelly.on('update-device-status', (deviceId, status) => {
    // ......
});
```

**Comment by Apollon77** [comment]
nneeeeeeee ... node_coap/lib/agent.js meinte ich!!

**Comment by schmupu** [comment]
hat leider auch nicht geholfen:

```
Agent.prototype._init = function initSock(socket) {
  if (this._sock) {
    return
  }

  
  var that = this
  this._sock = socket || dgram.createSocket(this._opts.type)
  this._sock.on('error', function(err) {
    // we are skipping DNS errors
    if(!hasDNSbug || err.code !== 'ENOTFOUND')
      that.emit('error', err)
  })
// ....
```
Gleicher Fehler wieder :-(

**Comment by Apollon77** [comment]
Alao laut Log kommt der Fehler genau bei dem coap.request in https://github.com/Apollon77/shelly-iot/blob/master/index.js#L222 ... magst Du bei node_coap mal ein issue auf machen? und sag das auch ein hochschieben des error handlers nichts gebracht hat. Vllt haben die noch eine Idee

**Comment by schmupu** [comment]
Issue: https://github.com/mcollina/node-coap/issues/209
